export type MediaKind = 'video' | 'audio';
export type VideoContainer = 'mp4' | 'mkv' | 'webm';
export type AudioContainer = 'mp3' | 'flac' | 'wav' | 'm4a';
export type SponsorBlockMode = 'off' | 'mark' | 'remove';

export interface VideoQuality { maxHeight: number; fps: number; }
export interface AudioQuality { bitrateKbps: number; normalize: boolean; }

export type SubtitleMode = 'sidecar' | 'embed' | 'burnin';

export interface SubtitleOptions {
  languages: string[];
  autoGenerated: boolean;
  mode: SubtitleMode;
  format: 'srt' | 'vtt';
}

export interface ChapterInfo {
  title: string | null;
  start: number;
  end: number;
}

export interface SubtitleTrack {
  lang: string;
  name: string | null;
  kind: 'manual' | 'auto';
  formats: string[];
}

export interface SponsorSegment {
  uuid: string;
  category: string;
  actionType: string; // skip | mute | chapter | poi | full
  start: number;
  end: number;
  videoDuration: number | null;
  votes: number | null;
  locked: number | null;
  description: string | null;
}

export interface MetadataOptions {
  embedThumbnail: boolean;
  keepChapters: boolean;
  embedMetadata: boolean;
}

export interface SponsorBlockOptions {
  mode: SponsorBlockMode;
  categories: string[]; // sponsor, intro, outro, selfpromo, interaction, music_offtopic, preview, filler
}

export interface NetworkOptions {
  proxy: string | null;
  rateLimit: string | null;
  cookiesFromBrowser: string | null;
  concurrentFragments: number;
}

export interface PlaylistOptions {
  enabled: boolean;
  items: string | null;
}

export interface DownloadOptions {
  url: string;
  outputDir: string;
  kind: MediaKind;
  videoContainer?: VideoContainer;
  audioContainer?: AudioContainer;
  video?: VideoQuality;
  audio?: AudioQuality;
  subtitles?: SubtitleOptions;
  metadata: MetadataOptions;
  sponsorblock: SponsorBlockOptions;
  network: NetworkOptions;
  playlist: PlaylistOptions;
}

export interface ProgressUpdate {
  id: string;
  status: 'downloading' | 'finished' | 'error' | string;
  downloaded: number;
  total: number | null;
  percent: number | null;
  speedBps: number | null;
  etaSecs: number | null;
  title: string | null;
}

export interface DownloadStarted { id: string; url: string; }
export interface DownloadFinished {
  id: string;
  success: boolean;
  exitCode: number | null;
  error: string | null;
  canceled: boolean;
  outputPath: string | null;
}
export interface DownloadLog { id: string; stream: 'stdout' | 'stderr'; line: string; }

export type DownloadStatus =
  | 'queued'
  | 'downloading'
  | 'paused'
  | 'finished'
  | 'error'
  | 'canceled';

export interface DownloadItem {
  id: string;
  url: string;
  title: string | null;
  status: DownloadStatus;
  percent: number;
  downloaded: number;
  total: number | null;
  speedBps: number | null;
  etaSecs: number | null;
  error: string | null;
  attempts: number;
  queuePosition: number;
  startedAt: number;
  outputPath: string | null;
}

/** Persisted shape from the backend (matches Rust `DownloadRecord`). */
export interface DownloadRecord {
  id: string;
  url: string;
  title: string | null;
  status: DownloadStatus | string;
  percent: number;
  downloaded: number;
  total: number | null;
  error: string | null;
  outputPath: string | null;
  attempts: number;
  queuePosition: number;
  createdAt: string;
  startedAt: string | null;
  finishedAt: string | null;
  optionsJson: string;
}

export interface QueueChanged {
  maxConcurrent: number;
  active: number;
  queued: number;
}
