<script lang="ts">
  import { fade, fly } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';
  import { Download, Sparkles } from 'lucide-svelte';
  import UrlInput from '$lib/components/UrlInput.svelte';
  import AdvancedPanel from '$lib/components/AdvancedPanel.svelte';
  import QueueView from '$lib/components/QueueView.svelte';
  import EnvCheck from '$lib/components/EnvCheck.svelte';
  import HeroCard from '$lib/components/HeroCard.svelte';
  import { onMount } from 'svelte';
  import { FolderOpen, Folder } from 'lucide-svelte';
  import { ipc } from '$lib/ipc';
  import { probe } from '$lib/stores/probe';
  import type { DownloadOptions } from '$lib/types';

  let loading = $state(false);
  let lastError = $state<string | null>(null);
  let urlDraft = $state('');

  // Debounced probe whenever the user types a (looks-like-YouTube) URL.
  $effect(() => {
    const u = urlDraft.trim();
    const ok = /^https?:\/\/(www\.)?(youtube\.com|youtu\.be|m\.youtube\.com|music\.youtube\.com)\/.+/i.test(u);
    probe.request(ok ? u : null);
  });

  // Auto-clamp selected resolution and Max FPS based on actual video metadata
  $effect(() => {
    if ($probe.status === 'ready' && $probe.data) {
      const heights = $probe.data.availableHeights;
      if (heights && heights.length > 0) {
        const maxAvailable = heights[0]; // descending order
        const currentHeight = options.video?.maxHeight ?? 1080;
        if (currentHeight > maxAvailable) {
          options.video = {
            ...(options.video ?? { fps: 60, maxHeight: 1080 }),
            maxHeight: maxAvailable
          };
        }
      }
      
      const fps = $probe.data.availableFps;
      if (fps && fps.length > 0) {
        const maxFps = Math.max(...fps);
        const currentFps = options.video?.fps ?? 60;
        if (currentFps > maxFps) {
          options.video = {
            ...(options.video ?? { fps: 60, maxHeight: 1080 }),
            fps: maxFps
          };
        }
      }
    }
  });

  let options = $state<DownloadOptions>({
    url: '',
    outputDir: '',  // resolved on mount via ipc.defaultDownloadDir()
    kind: 'video',
    videoContainer: 'mp4',
    audioContainer: 'mp3',
    video: { maxHeight: 1080, fps: 60 },
    audio: { bitrateKbps: 192, normalize: false },
    subtitles: { languages: [], autoGenerated: false, mode: 'sidecar', format: 'srt' },
    metadata: { embedThumbnail: true, keepChapters: true, embedMetadata: true },
    sponsorblock: { mode: 'off', categories: ['sponsor', 'selfpromo'] },
    network: { proxy: null, rateLimit: null, cookiesFromBrowser: null, concurrentFragments: 4 },
    playlist: { enabled: false, items: null }
  });

  async function start(url: string) {
    lastError = null;
    loading = true;
    try {
      // Make sure we have a real absolute output dir before enqueueing.
      if (!options.outputDir || options.outputDir.startsWith('~')) {
        try { options.outputDir = await ipc.defaultDownloadDir(); }
        catch (e) { /* leave as-is and let backend report */ }
      }
      await ipc.startDownload({ ...options, url });
    } catch (e) {
      lastError = String(e);
    } finally {
      loading = false;
    }
  }

  async function pickFolder() {
    try {
      const chosen = await ipc.pickOutputDirectory();
      if (chosen) options.outputDir = chosen;
    } catch (e) {
      lastError = String(e);
    }
  }

  onMount(async () => {
    try {
      options.outputDir = await ipc.defaultDownloadDir();
    } catch {
      options.outputDir = '~/Downloads/YTa-dlp';
    }
  });
</script>

<main class="mx-auto flex min-h-screen max-w-5xl flex-col px-6 py-12">
  <header class="mb-12 flex items-center justify-between" in:fade={{ duration: 400 }}>
    <div class="flex items-center gap-2.5">
      <div class="grid h-9 w-9 place-items-center rounded-xl overflow-hidden shadow-[0_8px_24px_-8px_hsl(var(--primary)/0.7)] border border-primary/20 bg-secondary">
        <img src="/logo.png" alt="YTa-dlp Logo" class="h-full w-full object-cover" />
      </div>
      <div class="leading-tight">
        <div class="text-sm font-semibold tracking-tight">YTa-dlp</div>
        <div class="text-[11px] text-muted-foreground">premium downloader · powered by yt-dlp</div>
      </div>
    </div>
    <div class="flex items-center gap-2">
      <EnvCheck />
      <div class="flex items-center gap-1.5 rounded-full border border-border/60 bg-secondary/40 px-3 py-1 text-[11px] text-muted-foreground">
        <Sparkles class="h-3 w-3 text-primary" /> Beta
      </div>
    </div>
  </header>

  <section class="flex flex-col items-center gap-10 py-8">
    <div class="text-center" in:fly={{ y: 12, duration: 500, easing: quintOut }}>
      <h1 class="bg-gradient-to-b from-foreground to-foreground/60 bg-clip-text text-4xl font-semibold tracking-tight text-transparent md:text-5xl">
        Download anything from YouTube.
      </h1>
      <p class="mt-3 text-sm text-muted-foreground md:text-base">
        Paste a link. Pick your format. We'll handle the rest — beautifully.
      </p>
    </div>

    <UrlInput onSubmit={start} onInput={(u) => (urlDraft = u)} {loading} />

    <!-- Output folder picker -->
    <div class="w-full max-w-2xl mx-auto -mt-6 flex items-center gap-2">
      <button
        type="button"
        onclick={pickFolder}
        class="flex items-center gap-1.5 rounded-lg border border-border/60 bg-secondary/40 px-3 py-1.5 text-[11px] text-muted-foreground hover:bg-secondary hover:text-foreground transition"
      >
        <Folder class="h-3 w-3" /> Save to
      </button>
      <div class="min-w-0 flex-1 truncate rounded-lg border border-border/60 bg-secondary/20 px-3 py-1.5 font-mono text-[11px] text-muted-foreground" title={options.outputDir}>
        {options.outputDir || '…'}
      </div>
      {#if options.outputDir}
        <button
          type="button"
          onclick={() => ipc.revealInFileManager(options.outputDir)}
          class="flex items-center gap-1 rounded-lg border border-border/60 bg-secondary/40 px-2 py-1.5 text-[11px] text-muted-foreground hover:text-foreground transition"
          title="Open folder"
        >
          <FolderOpen class="h-3 w-3" />
        </button>
      {/if}
    </div>

    <!-- Beautiful Video details drawer / HeroCard -->
    {#if $probe.status !== 'idle'}
      <div in:fly={{ y: -4, duration: 200 }} class="w-full max-w-2xl mx-auto -mt-6">
        {#if $probe.status === 'loading'}
          <div class="flex items-center justify-between rounded-lg border border-border/60 bg-secondary/40 px-3 py-1.5 text-[11px] text-muted-foreground">
            <span>Analyzing video…</span>
            <span class="font-mono">probing</span>
          </div>
        {:else if $probe.status === 'error'}
          <div class="flex items-center justify-between rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-1.5 text-[11px] text-destructive-foreground">
            <span class="truncate">Probe failed: {$probe.error}</span>
          </div>
        {:else if $probe.status === 'ready' && $probe.data}
          <HeroCard data={$probe.data} />
        {/if}
      </div>
    {/if}

    <AdvancedPanel bind:options />

    {#if lastError}
      <div in:fly={{ y: 8 }} class="rounded-xl border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive-foreground">
        {lastError}
      </div>
    {/if}
  </section>

  <QueueView />
</main>
