<script lang="ts">
  import { fade, slide } from 'svelte/transition';
  import { quintOut } from 'svelte/easing';
  import { Loader2, Search, Sparkles, X, CheckCircle2, Subtitles } from 'lucide-svelte';
  import { probe } from '$lib/stores/probe';
  import type { SubtitleOptions, SubtitleMode, SubtitleTrack, VideoContainer } from '$lib/types';
  import { cn } from '$lib/utils';

  interface Props {
    subtitles: SubtitleOptions;
    container: VideoContainer | undefined;
  }
  let { subtitles = $bindable(), container }: Props = $props();

  let query = $state('');

  // Group tracks: manual first, then auto. We honor the user's `autoGenerated` toggle for filtering.
  const tracks = $derived(($probe.data?.subtitles ?? []) as SubtitleTrack[]);
  const filteredTracks = $derived.by(() => {
    const q = query.trim().toLowerCase();
    return tracks
      .filter((t) => subtitles.autoGenerated || t.kind === 'manual')
      .filter((t) => {
        if (!q) return true;
        return (
          t.lang.toLowerCase().includes(q) ||
          (t.name ?? '').toLowerCase().includes(q)
        );
      });
  });

  const manualCount = $derived(tracks.filter((t) => t.kind === 'manual').length);
  const autoCount   = $derived(tracks.filter((t) => t.kind === 'auto').length);

  function toggleLang(lang: string) {
    const has = subtitles.languages.includes(lang);
    subtitles.languages = has
      ? subtitles.languages.filter((l) => l !== lang)
      : [...subtitles.languages, lang];
  }

  function setMode(mode: SubtitleMode) {
    subtitles.mode = mode;
  }

  // Burn-in / embed are only sensible for video containers that support text tracks.
  const embedSupported = $derived(container === 'mp4' || container === 'mkv');
  const burnInDisabledReason = $derived.by(() => {
    if (!container) return null;
    if (container === 'webm') return 'WebM container — burn-in only available for MP4/MKV outputs.';
    return null;
  });

  const modes: Array<{ id: SubtitleMode; label: string; hint: string }> = [
    { id: 'sidecar', label: 'Sidecar',  hint: 'Save as separate .srt/.vtt file' },
    { id: 'embed',   label: 'Embed',    hint: 'Soft track inside the container' },
    { id: 'burnin',  label: 'Burn-in',  hint: 'Hardcoded into the video stream' }
  ];
</script>

<div class="space-y-4">
  <!-- Mode selector -->
  <div>
    <div class="mb-1.5 text-[11px] uppercase tracking-wide text-muted-foreground">Mode</div>
    <div class="grid grid-cols-3 gap-1.5">
      {#each modes as m (m.id)}
        {@const disabled =
          (m.id === 'embed'  && !embedSupported && !!container) ||
          (m.id === 'burnin' && !!burnInDisabledReason)}
        <button
          type="button"
          onclick={() => !disabled && setMode(m.id)}
          {disabled}
          class={cn(
            'group relative flex flex-col items-start gap-0.5 rounded-lg border px-3 py-2 text-left text-xs transition',
            subtitles.mode === m.id
              ? 'border-primary bg-primary/10 text-foreground'
              : 'border-border/60 text-muted-foreground hover:bg-muted',
            disabled && 'cursor-not-allowed opacity-50'
          )}
          title={disabled && m.id === 'burnin' ? burnInDisabledReason ?? '' : m.hint}
        >
          <span class="font-medium">{m.label}</span>
          <span class="text-[10px] text-muted-foreground">{m.hint}</span>
          {#if subtitles.mode === m.id}
            <CheckCircle2 class="absolute right-2 top-2 h-3 w-3 text-primary" />
          {/if}
        </button>
      {/each}
    </div>
  </div>

  <!-- Track selector -->
  <div>
    <div class="mb-1.5 flex items-center justify-between text-[11px] uppercase tracking-wide text-muted-foreground">
      <div class="flex items-center gap-2">
        <span>Tracks</span>
        {#if $probe.status === 'loading'}
          <span class="inline-flex items-center gap-1 normal-case text-muted-foreground">
            <Loader2 class="h-3 w-3 animate-spin" /> probing…
          </span>
        {:else if $probe.status === 'ready' && tracks.length > 0}
          <span class="normal-case text-muted-foreground">
            {manualCount} manual · {autoCount} auto
          </span>
        {/if}
      </div>
      <label class="flex items-center gap-1.5 normal-case">
        <input type="checkbox" bind:checked={subtitles.autoGenerated} />
        <span class="text-muted-foreground">Auto-generated</span>
      </label>
    </div>

    {#if $probe.status === 'idle'}
      <div class="rounded-lg border border-dashed border-border/60 px-3 py-4 text-center text-[11px] text-muted-foreground">
        Paste a YouTube URL above to discover available subtitle tracks.
      </div>
    {:else if $probe.status === 'error'}
      <div class="rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-[11px] text-destructive-foreground">
        Probe failed: {$probe.error}
      </div>
    {:else if tracks.length === 0 && $probe.status === 'ready'}
      <div class="rounded-lg border border-dashed border-border/60 px-3 py-4 text-center text-[11px] text-muted-foreground">
        No subtitle tracks reported by yt-dlp for this video.
      </div>
    {:else}
      <!-- Selected langs as chips -->
      {#if subtitles.languages.length > 0}
        <div in:slide={{ duration: 180 }} class="mb-2 flex flex-wrap gap-1">
          {#each subtitles.languages as lang (lang)}
            <button
              type="button"
              onclick={() => toggleLang(lang)}
              class="inline-flex items-center gap-1 rounded-full border border-primary/40 bg-primary/15 px-2 py-0.5 text-[11px] text-foreground transition hover:bg-primary/25"
            >
              <Subtitles class="h-3 w-3" />
              <span class="font-mono">{lang}</span>
              <X class="h-3 w-3 opacity-60" />
            </button>
          {/each}
          <button
            type="button"
            onclick={() => (subtitles.languages = [])}
            class="text-[11px] text-muted-foreground hover:text-foreground px-1"
          >
            Clear
          </button>
        </div>
      {/if}

      <!-- Search box -->
      <div class="mb-2 flex items-center gap-2 rounded-lg border border-border/60 bg-secondary/40 px-2 py-1.5">
        <Search class="h-3 w-3 text-muted-foreground" />
        <input
          type="text"
          bind:value={query}
          placeholder="Filter by language code or name…"
          class="flex-1 bg-transparent text-xs outline-none placeholder:text-muted-foreground/70"
        />
        {#if query}
          <button onclick={() => (query = '')} class="text-muted-foreground hover:text-foreground">
            <X class="h-3 w-3" />
          </button>
        {/if}
      </div>

      <!-- Track grid -->
      <div class="max-h-44 overflow-y-auto rounded-lg border border-border/60 bg-secondary/20 p-1.5">
        {#if filteredTracks.length === 0}
          <div class="px-2 py-3 text-center text-[11px] text-muted-foreground">No tracks match "{query}".</div>
        {:else}
          <div class="grid grid-cols-2 gap-1 md:grid-cols-3">
            {#each filteredTracks as t (t.kind + ':' + t.lang)}
              {@const selected = subtitles.languages.includes(t.lang)}
              <button
                type="button"
                onclick={() => toggleLang(t.lang)}
                class={cn(
                  'group flex items-center justify-between gap-1 rounded-md border px-2 py-1 text-left text-[11px] transition',
                  selected
                    ? 'border-primary bg-primary/15 text-foreground'
                    : 'border-transparent text-muted-foreground hover:bg-muted hover:text-foreground'
                )}
                title={t.formats.length ? `Formats: ${t.formats.join(', ')}` : undefined}
              >
                <span class="min-w-0 flex items-center gap-1.5">
                  <span class="font-mono shrink-0">{t.lang}</span>
                  {#if t.name}<span class="truncate">{t.name}</span>{/if}
                </span>
                <span class={cn(
                  'shrink-0 rounded-sm px-1 py-px text-[9px] uppercase tracking-wide',
                  t.kind === 'manual' ? 'bg-emerald-500/15 text-emerald-400' : 'bg-amber-500/15 text-amber-400'
                )}>{t.kind === 'manual' ? 'orig' : 'auto'}</span>
              </button>
            {/each}
          </div>
        {/if}
      </div>

      <!-- "all" shortcut and format -->
      <div class="mt-2 flex items-center justify-between">
        <button
          type="button"
          onclick={() => {
            const hasAll = subtitles.languages.includes('all');
            subtitles.languages = hasAll ? [] : ['all'];
          }}
          class={cn(
            'inline-flex items-center gap-1 rounded-md border px-2 py-1 text-[11px] transition',
            subtitles.languages.includes('all')
              ? 'border-primary bg-primary/15 text-foreground'
              : 'border-border/60 text-muted-foreground hover:bg-muted'
          )}
        >
          <Sparkles class="h-3 w-3" /> All languages
        </button>

        <label class="flex items-center gap-1.5 text-[11px] text-muted-foreground">
          Sidecar format
          <select
            bind:value={subtitles.format}
            class="rounded border border-border/60 bg-secondary/50 px-1.5 py-0.5 text-[11px]"
          >
            <option value="srt">SRT</option>
            <option value="vtt">VTT</option>
          </select>
        </label>
      </div>
    {/if}
  </div>
</div>
